In [2]:
import numpy as np
import pandas as pd

x= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
y=np.reshape(x,(3,3))
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
for i in range(0,len(x)):
    if(x[i]%2==1):
        x[i]=-1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8]


In [12]:
x[x%2==1]=-1
print(x)


[ 0 -1  2 -1  4 -1  6 -1  8]


In [13]:


x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [19]:
p= np.arange(100).reshape(5,-1) #as many columns as necessary to fit data; but 5 rows only
print(p)
q=p[:, :4]
print(q)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [4]:
arr=np.random.randint(30,41,size=10)
print(arr)

[33 30 31 39 37 34 40 32 37 36]


In [6]:
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10))
B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))

A=np.array(A)
B=np.array(B)
C=A+B
E=A-B
print(C)
print()
print(E)


[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [8]:
sum_a=np.sum(A)
sum_cols_b=np.sum(B,axis=0)
sum_rows_c=np.sum(C,axis=1)
print(sum_a)
print(sum_cols_b)
print(sum_rows_c)


46
[12 15 19]
[31 30 31]


In [10]:
print (A)
print(B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]


In [ ]:
D=A@B 
print(D)

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


In [ ]:
print(C)
E_sorted = np.sort(C, axis=None).reshape(C.shape)
print(E_sorted)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]


In [18]:
print(C)
E=np.reshape(C,(1,-1))
E=np.sort(E)
E=np.reshape(E,(3,3))
print(E)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]


In [19]:
print(np.transpose(E))

[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]


In [20]:
print(E.T)

[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
